# Generated by Django 6.0.7 on 2026-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('codcarpeta', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('year_start', models.CharField(max_length=4)),
                ('year_end', models.CharField(blank=True, max_length=4, null=True)),
                ('notas', models.BooleanField(default=False)),
                ('mat_sem', models.BooleanField(default=False)),
                ('rec_pago', models.BooleanField(default=False)),
                ('folio', models.IntegerField(default=0)),
                ('modelo', models.BooleanField(default=True)),
                ('observa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula_ciudadania', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipocc', models.CharField(max_length=20)),
                ('rdoc', models.BooleanField(default=False)),
                ('programa', models.CharField(max_length=30)),
                ('codcarpeta', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
