# Generated by Django 6.0.7 on 2026-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
