# Generated by Django 6.1.1 on 2026-09-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_carpeta_activo_carpeta_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='codcarpeta',
        ),
        migrations.AddField(
            model_name='carpeta',
            name='estudiante',
            field=models.ForeignKey(default=2425424, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='estudiantes.estudiante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='codcarpeta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
